apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-data-pvc  # This MUST match the 'claimName' in your Deployment.yaml
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi      # Adjust size as needed (e.g., 5Gi)
